Created form base for Index.html
jordienr/tax-app pull request #3
Opened 2023-01-23 18:10 UTC by Dualvicc

Lavin compadre.
Revisad los IDs que acordamos para conectarlo todo

2023-01-23 18:11 UTC, guillemrima commented
Unbelievable. 
This must be merged for sure.

2023-01-23 20:06 UTC, jordienr requested changes
Check comments

2023-01-23 20:06 UTC, jordienr commented on index.html
> +        <label for="docNum">Número de Documento</label><br>
Veo que haces `<br>` para hacer saltos de lineas.

Esto te pasa por que `<label>` y `<input>` son elementos con `display: inline` de CSS base. 

Para que ocupen todo el espacio horizontal y fuerzen al siguiente elemento a estar en la siguiente línea tienen que ser `display: block`

Si encapsulas los elementos dentro de `<div>` (que es de tipo `block`) quedará un poco más limpio.
```html
<div class="input-group">
    <label>...</label>
    <input... />
</div>
```

Después puedes crear una clase `.input-group` para colocarlos con `flex`

```css
.input-group {
    display: flex; // Cambia de display block a flex
    flex-direction: column; // Hace que la dirección del flex sea horizontal
}
```

2023-01-23 20:06 UTC, jordienr commented on index.html
> +                <input type="radio" id="Gasto" name="docType">
La `id` está en castellano y capitalizada

2023-01-24 08:58 UTC, BernatBC06 commented on index.html
> +        <label for="docNum">Número de Documento</label><br>
It smells like coomer in here

2023-01-24 11:58 UTC, Dualvicc commented on index.html
> +
Pero el for no esta dirigido a un id? Es decir es aposta para que conecten

2023-01-24 17:13 UTC, guillemrima commented on index.html
> +            <input type="text" id="docBaseTax" placeholder="€">
Sugiero modificar el tipo del Input de `text` a `number` para evitar que el usuario pueda introducir números

2023-01-24 21:31 UTC, jordienr commented on index.html
> +            <input type="text" id="docBaseTax" placeholder="€">
También puedes mirar que en el móvil salga el teclado numérico en lugar de el de texto

2023-01-24 21:55 UTC, guillemrima commented on index.html
> +                    <input type="radio" id="expense" name="docType">
Me viene bien para el script que le agregues un `value` a los inputs de tipo `radio` para que pueda recoger su valor.
`<input type="radio" id="expense name="docType" value="Gasto">`

2023-01-24 21:55 UTC, guillemrima commented on index.html
> +                    <input type="radio" id="income" name="docType">
`<input type="radio" id="income" name="docType" value="Ingreso">`

2023-01-24 21:55 UTC, guillemrima commented on index.html
> +                    <input type="radio" id="21" name="docTax">
`<input type="radio" id="21 name="docTax" value="21">`

2023-01-24 21:55 UTC, guillemrima commented on index.html
> +                    <input type="radio" id="10" name="docTax">
`<input type="radio" id="10" name="docTax" value="10">`

2023-01-24 21:55 UTC, guillemrima commented on index.html
> +                    <input type="radio" id="4" name="docTax">
`<input type="radio" id="4" name="docTax" value="4">`

2023-01-25 09:25 UTC, Dualvicc commented on index.html
> +                    <input type="radio" id="4" name="docTax">
oido cocina

2023-01-25 09:42 UTC, Dualvicc commented on index.html
> +                    <input type="radio" id="10" name="docTax">
Resuelto

2023-01-25 09:43 UTC, Dualvicc commented on index.html
> +                <input type="radio" id="Gasto" name="docType">
Resuelto

2023-01-25 09:43 UTC, Dualvicc commented on index.html
> +                <input type="radio" id="Ingreso" name="docType">
Resuelto

2023-01-25 09:53 UTC, jordienr approved these changes
lgtm

2023-01-25 09:53 UTC, merged