Feat/scaffold budget html
jordienr/tax-app pull request #32
Opened 2023-02-04 15:58 UTC by guillemrima

En esta PR se añade:

- La estructura `HTML` para la ruta `/budget`.
- La hoja de estilos para la ruta `/budget`.
- Nuevos iconos para la ruta `/budget` en la carpeta `img`.

2023-02-06 17:26 UTC, jordienr requested changes

2023-02-06 17:26 UTC, jordienr commented on public/budget.html
> +    <link rel="stylesheet" href="./budget.css">
al final no hacemos lo de tener un css base y un css de la página? Rollo esto
```html
<link rel="stylesheet" href="./index.css">
<link rel="stylesheet" href="./budget.css">
```

y en todas las páginas se importaría index.css y {pagina}.css

2023-02-06 17:29 UTC, guillemrima commented on public/budget.html
> +    <link rel="stylesheet" href="./budget.css">
Sep, voy a organizarlo todo junto al Index y te hago un commit nuevo con los nuevos cambios.

2023-02-06 17:33 UTC, guillemrima commented on public/budget.html
> +    <link rel="stylesheet" href="./budget.css">
> al final no hacemos lo de tener un css base y un css de la página? Rollo esto
> ```html
> <link rel="stylesheet" href="./index.css">
> <link rel="stylesheet" href="./budget.css">
> ```
> 
> y en todas las páginas se importaría index.css y {pagina}.css

Sep, voy a organizarlo todo junto al Index y te hago un commit nuevo con los nuevos cambios.

2023-02-06 17:53 UTC, guillemrima commented
Listo, **`Index.css`** ya contiene los valores generales de la app.
Es un poco confuso porque **`"style.css`**" corresponde a "**`index.html`**" e **`index.css`** son los valores generales, debería girar los nombres pero no se si se va a romper algo al hacerlo.

2023-02-06 20:20 UTC, jordienr commented
Al base lo puedes llamar base.css o globals.css

2023-02-07 09:44 UTC, guillemrima commented
Listo, he renombrado las hojas de estilo. 
La general pasa a llamarse `globals.css` y las dedicadas tienen el mismo nombre que su html.

2023-02-07 10:55 UTC, jordienr approved these changes

2023-02-07 10:55 UTC, merged