Finalized script to get data from formulary & convert it into JSON object
jordienr/tax-app pull request #4
Opened 2023-01-24 21:48 UTC by guillemrima

El script está a la espera de que Willy me confirme el **endpoint** al que irá dirigida la información del formulario.

De momento esta es la **PR** que sugiero que implementemos al repositorio principal.

He confirmado la funcionalidad del **script** y de momento:
-El script recoge los inputs del formulario mediante la función `getData()`.
-El script crea un objeto JSON con los valores de los inputs mediante la función `createJsonData()`.

Para el próximo **PR** incorporaré la función de mandar el JSON al **back-end** y las validaciones de cada campo para no permitir campos vacios ni valores no admitidos.

He puesto como sugerencia al PR del `Created form base for Index.html` la necesidad de agregar `value` a los inputs de tipo `radio` para que puedan ser recogidos en el script.

Creo que eso es todo shavales 👍

2023-01-25 10:03 UTC, jordienr requested changes

2023-01-25 10:03 UTC, jordienr commented on public/index-script.js
> +const getData = () => {
Hay una clase de JS que se llama "FormData" que se puede usar para extraer datos de un `<form>` https://javascript.info/formdata#formdata-methods

Puedes probar a refactorizar este método para que lo use?

2023-01-26 08:52 UTC, Dualvicc commented on public/index-script.js
> +function sendData(data) {
Estaria bien poner los cierres "}" al mismo level para hacer mas facil la lectura de codigo. Creo que solo pasa en la linea 48

2023-01-26 09:23 UTC, guillemrima commented on public/index-script.js
> +function sendData(data) {
Corregido.

2023-01-26 09:24 UTC, guillemrima commented on public/index-script.js
> +let numEl = document.getElementById("docNum");
Corregido.

2023-01-26 15:57 UTC, guillemrima commented on public/index-script.js
> +const getData = () => {
Corregido.

2023-01-26 17:22 UTC, jordienr approved these changes

2023-01-26 19:37 UTC, guillemrima commented
Conflicto resuelto, creo.

2023-01-27 16:52 UTC, merged